SET IDENTITY_INSERT dbUITerm ON;

INSERT INTO dbUITerm (Id, Name, Description) VALUES(1, 'Classification', 'Classification');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(2, 'Id', 'Id');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(3, 'Name', 'Name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(4, 'Create new classification', 'Create new classification');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(5, 'Add', 'Add');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(6, 'Add language', 'Add language');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(7, 'Add values', 'Add values');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(8, 'Alphabetically', 'Alphabetically');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(9, 'Back to classification levels', 'Back to classification levels');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(10, 'Back to classification values', 'Back to classification values');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(11, 'Back to classifications', 'Back to classifications');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(12, 'Can link', 'Can link');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(13, 'Cancel', 'Cancel');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(14, 'Classification languages', 'Classification languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(15, 'Classification levels', 'Classification levels');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(16, 'Classification value languages', 'Classification value languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(17, 'Content type', 'Content type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(18, 'Create new classification level', 'Create new classification level');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(19, 'Create new value', 'Create new value');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(20, 'Date level', 'Date level');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(21, 'Delete', 'Delete');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(22, 'Description', 'Description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(23, 'Drop down name', 'Drop down name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(24, 'Edit', 'Edit');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(25, 'Edit classification', 'Edit classification');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(26, 'Edit classification level', 'Edit classification level');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(27, 'Edit language', 'Edit language');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(28, 'Edit value', 'Edit value');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(29, 'Has dropdown', 'Has dropdown');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(30, 'Header description', 'Header description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(31, 'Header name', 'Header name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(32, 'In drop down', 'In drop down');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(33, 'Language', 'Language');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(34, 'Languages', 'Languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(35, 'Logout', 'Logout');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(36, 'Menu name', 'Menu name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(37, 'Mouse over', 'Mouse over');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(38, 'New value', 'New value');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(39, 'On the fly', 'On the fly');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(40, 'Open', 'Open');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(41, 'Organization', 'Organization');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(42, 'Organization type', 'Organization type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(43, 'Page description', 'Page description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(44, 'Page name', 'Page name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(45, 'Page type', 'Page type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(46, 'Pages', 'Pages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(47, 'Process template field types', 'Process template field types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(48, 'Process template groups', 'Process template groups');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(49, 'Process templates', 'Process templates');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(50, 'Projects', 'Projects');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(51, 'Roles', 'Roles');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(52, 'Save', 'Save');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(53, 'Section types', 'Section types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(54, 'Settings', 'Settings');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(55, 'Setup wizard', 'Setup wizard');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(56, 'Status', 'Status');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(57, 'Terms', 'Terms');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(58, 'Topic name', 'Topic name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(59, 'Classifications', 'Classifications');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(60, 'Add new classification', 'Add new classification');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(61, 'Levels', 'Levels');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(62, 'Sequence', 'Sequence');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(63, 'Classification level languages', 'Classification level languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(64, 'Update', 'Update');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(65, 'Users', 'Users');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(66, 'Values', 'Values');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(67, 'Delete classification', 'Delete classification');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(68, 'Creator', 'Creator');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(69, 'Modifier', 'Modifier');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(70, 'Content types', 'Content types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(71, 'Create new content type', 'Create new content type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(72, 'Edit content type', 'Edit content type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(73, 'Create content type', 'Create content type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(74, 'Content type languages', 'Content type languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(75, 'Back to content types', 'Back to content types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(76, 'Delete language', 'Delete language');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(77, 'Organizations', 'Organizations');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(78, 'Add organization', 'Add organization');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(79, 'Create new organization', 'Create new organization');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(80, 'Organization languages', 'Organization languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(81, 'Back to organization', 'Back to organization');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(82, 'Create organization', 'Create organization');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(83, 'Type', 'Type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(84, 'Parent organization', 'Parent organization');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(85, 'Organization types', 'Organization types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(86, 'Create new organization type', 'Create new organization type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(87, 'Edit organization type', 'Edit organization type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(88, 'Organization type languages', 'Organization type languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(89, 'Back to organization types', 'Back to organization types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(90, 'Sections', 'Sections');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(91, 'Create page', 'Create page');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(92, 'Edit page', 'Edit page');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(93, 'Page sections', 'Page sections');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(94, 'Create new page section', 'Create new page section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(95, 'Back to pages', 'Back to pages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(96, 'Edit page section', 'Edit page section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(97, 'Back to page sections', 'Back to page sections');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(98, 'Create page section', 'Create page section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(99, 'Title description', 'Title description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(100, 'Title', 'Title');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(101, 'Show title', 'Show title');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(102, 'Show title description', 'Show title description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(103, 'Show content type title', 'Show content type title');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(104, 'Show content type description', 'Show content type description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(105, 'Page types', 'Page types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(106, 'Create new page type', 'Create new page type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(107, 'Edit page type', 'Edit page type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(108, 'Create page type', 'Create page type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(109, 'Page type languages', 'Page type languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(110, 'Back to page types', 'Back to page types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(111, 'Add project', 'Add project');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(112, 'Create new project', 'Create new project');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(113, 'Edit project', 'Edit project');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(114, 'Create project', 'Create project');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(115, 'Project languages', 'Project languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(116, 'Back to projects', 'Back to projects');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(117, 'Page section types', 'Page section types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(118, 'Create new page section type', 'Create new page section type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(119, 'Edit page section type', 'Edit page section type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(120, 'Create page section type', 'Create page section type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(121, 'Index section', 'Index section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(122, 'Page section type languages', 'Page section type languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(123, 'Back to page section types', 'Back to page section types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(124, 'Relations', 'Relations');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(125, 'Add new role', 'Add new role');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(126, 'Edit user', 'Edit user');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(127, 'Create user', 'Create user');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(128, 'Email', 'Email');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(129, 'Default language', 'Default language');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(130, 'Country', 'Country');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(131, 'Password', 'Password');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(132, 'Confirm password', 'Confirm password');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(133, 'User projects', 'User projects');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(134, 'Back to users', 'Back to users');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(135, 'Add user to project', 'Add user to project');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(136, 'Project', 'Project');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(137, 'Edit role', 'Edit role');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(138, 'Manage users', 'Manage users');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(139, 'Rights', 'Rights');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(140, 'Manage rights', 'Manage rights');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(141, 'Manage users to role', 'Manage users to role');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(142, 'Role Id', 'Role Id');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(143, 'User name', 'User name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(144, 'Manage rights to role', 'Manage rights to role');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(145, 'Selected', 'Selected');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(146, 'Claim type', 'Claim type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(147, 'Claim value', 'Claim value');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(148, 'Role', 'Role');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(149, 'Create new role', 'Create new role');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(150, 'Role name', 'Role name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(151, 'Create role', 'Create role');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(152, 'Fields', 'Fields');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(153, 'Flow', 'Flow');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(154, 'Edit process template', 'Edit process template');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(155, 'Create new process template', 'Create new process template');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(156, 'Process template group', 'Process template group');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(157, 'Process template fields', 'Process template fields');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(158, 'Steps', 'Steps');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(159, 'Create new process template field', 'Create new process template field');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(160, 'Edit process template field', 'Edit process template field');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(161, 'Add process template field', 'Add process template field');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(162, 'Data type', 'Data type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(163, 'Linked table', 'Linked table');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(164, 'Steps for field', 'Steps for field');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(165, 'Edit step field settings', 'Edit step field settings');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(166, 'Process template field languages', 'Process template field languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(167, 'Back to process template fields', 'Back to process template fields');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(168, 'Process template flows', 'Process template flows');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(169, 'Conditions', 'Conditions');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(170, 'Create new process template flow', 'Create new process template flow');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(171, 'Back to process templates', 'Back to process templates');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(172, 'Edit process template flow', 'Edit process template flow');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(173, 'Condition relation', 'Condition relation');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(174, 'From step', 'From step');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(175, 'To step', 'To step');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(176, 'Process template flow languages', 'Process template flow languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(177, 'Flow conditions', 'Flow conditions');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(178, 'Char', 'Char');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(179, 'Create new process template flow condition', 'Create new process template flow condition');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(180, 'Back to process template flows', 'Back to process template flows');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(181, 'Create new process template group', 'Create new process template group');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(182, 'Edit process template group', 'Edit process template group');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(183, 'Create process template group', 'Create process template group');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(184, 'Process template group languages', 'Process template group languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(185, 'Back to process template groups', 'Back to process template groups');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(186, 'Create content', 'Create content');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(187, 'Content title', 'Content title');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(188, 'Content description', 'Content description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(189, 'Content status', 'Content status');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(190, 'Content organization', 'Content organization');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(191, 'Content project', 'Content project');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(192, 'Foreign name', 'Foreign name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(193, 'ISO6391', 'ISO6391');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(194, 'ISO6392', 'ISO6392');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(195, 'Back to process fields', 'Back to process fields');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(196, 'Fields for step', 'Fields for step');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(197, 'Back to steps', 'Back to steps');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(198, 'Process template steps', 'Process template steps');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(199, 'Create new process template step', 'Create new process template step');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(200, 'Edit step', 'Edit step');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(201, 'Add step', 'Add step');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(202, 'Process template step languages', 'Process template step languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(203, 'Add new language', 'Add new language');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(204, 'Active', 'Active');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(205, 'Int', 'Int');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(206, 'String', 'String');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(207, 'Date', 'Date');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(208, 'Edit setting', 'Edit setting');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(209, 'Process template field type languages', 'Process template field type languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(210, 'Edit process template field type', 'Edit process template field type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(211, 'Delete process template field type', 'Delete process template field type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(212, 'Create process template field type', 'Create process template field type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(213, 'Back to process template field types', 'Back to process template field types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(214, 'User organization type', 'User organization type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(215, 'User organization type languages', 'User organization type languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(216, 'Add user organization type language', 'Add user organization type language');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(217, 'Back to user organization types', 'Back to user organization types');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(218, 'CreatedDate', 'CreatedDate');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(219, 'ModifiedDate', 'ModifiedDate');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(220, 'Delete content type', 'Delete content type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(221, 'Delete organization', 'Delete organization');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(222, 'Delete organization type', 'Delete organization type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(223, 'Delete page', 'Delete page');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(224, 'Delete page section', 'Delete page section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(225, 'Has paging', 'Has paging');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(226, 'Max content', 'Max content');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(227, 'One two columns', 'One two columns');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(228, 'Page section languages', 'Page section languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(229, 'Page languages', 'Page languages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(231, 'Drop down sequence', 'Drop down sequence');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(232, 'Default page', 'Default page');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(233, 'Preference', 'Preference');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(234, 'User project type', 'User project type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(235, 'User relation type', 'User relation type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(236, 'login', 'login');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(237, 'Register', 'Register');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(238, 'Add content', 'Add content');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(239, 'Content', 'Content');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(240, 'Calendar', 'Calendar');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(241, 'Chat', 'Chat');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(242, 'Conference', 'Conference');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(243, 'Favorites', 'Favorites');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(244, 'Game', 'Game');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(245, 'Add process', 'Add process');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(246, 'Process', 'Process');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(247, 'Add todo', 'Add todo');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(248, 'Todo', 'Todo');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(249, 'Search', 'Search');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(250, 'Classification pages', 'Classification pages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(251, 'Create new classification page', 'Create new classification page');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(252, 'Edit classification page', 'Edit classification page');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(253, 'Show title name', 'Show title name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(254, 'Title name', 'Title name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(255, 'Add classification page', 'Add classification page');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(256, 'Delete classification page', 'Delete classification page');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(257, 'Back to classification pages', 'Back to classification pages');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(258, 'Classification page sections', 'Classification page sections');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(259, 'Create new classification page section', 'Create new classification page section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(260, 'Edit classification page section', 'Edit classification page section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(261, 'Section type', 'Section type');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(262, 'Show section title name', 'Show section title name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(263, 'Show section title description', 'Show section title description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(264, 'Show content type title name', 'Show content type title name');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(265, 'Show content type title description', 'Show content type title description');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(266, 'Sort by', 'Sort by');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(267, 'Add classification page section', 'Add classification page section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(268, 'Delete classification page section', 'Delete classification page section');
INSERT INTO dbUITerm (Id, Name, Description) VALUES(269, 'In Menu', 'In Menu');

SET IDENTITY_INSERT dbUITerm OFF;
